# Generated by Django 5.0.2 on 2024-02-19 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'restaurant')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user', 'restaurant')},
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
